### ISSUE TITLE
文件比较大传输，会报错，帮忙看看是什么原因？

### ISSUE THREAD

**Issue by Fantasy9619** [sazima/proxynt#21]
文件比较大传输，会报错，帮忙看看是什么原因？

2024-08-17 20:37:39,748 logger ERROR /home/project/home_svn/trunk/python/proxynt-master/server/websocket_handler.py on_message_async 160 : Traceback (most recent call last):
File "/home/project/home_svn/trunk/python/proxynt-master/server/websocket_handler.py", line 102, in on_message_async
await tcp_forward_client.send_to_socket(uid, data['data'])
File "/home/project/home_svn/trunk/python/proxynt-master/server/tcp_forward_client.py", line 203, in send_to_socket
await asyncio.get_event_loop().sock_sendall(socket_client, message)
File "/www/server/pyporject_evn/proxynt-master_venv/lib/python3.11/asyncio/selector_events.py", line 544, in sock_sendall
handle = self._add_writer(fd, self._sock_sendall, fut, sock,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/www/server/pyporject_evn/proxynt-master_venv/lib/python3.11/asyncio/selector_events.py", line 302, in _add_writer
key = self._selector.get_key(fd)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/www/server/pyporject_evn/proxynt-master_venv/lib/python3.11/selectors.py", line 190, in get_key
return mapping[fileobj]
~~~~~~~^^^^^^^^^
File "/www/server/pyporject_evn/proxynt-master_venv/lib/python3.11/selectors.py", line 71, in __getitem__
fd = self._selector._fileobj_lookup(fileobj)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/www/server/pyporject_evn/proxynt-master_venv/lib/python3.11/selectors.py", line 225, in _fileobj_lookup
return _fileobj_to_fd(fileobj)
^^^^^^^^^^^^^^^^^^^^^^^
File "/www/server/pyporject_evn/proxynt-master_venv/lib/python3.11/selectors.py", line 42, in _fileobj_to_fd
raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1

**Comment by Fantasy9619** [comment]
找到问题了，客户端socket超时了，加大就可以了
