### ISSUE TITLE
在wss环境下服务端出现了报错，客户端无法正常映射端口至服务端。

### ISSUE THREAD

**Issue by MilkywayVainB** [sazima/proxynt#23]
大佬可以看看这个问题吗，环境是在wss的服务器环境，目前客户端这边已经设置了忽略ssl，但是服务端出现了报错。
<img width="835" alt="image" src="https://github.com/user-attachments/assets/9e217f12-9ca3-4638-8546-dfe05d4d957c">

服务端日志出现如下报错：
```
Traceback (most recent call last):
  File "/root/server/proxynt/server/websocket_handler.py", line 68, in write_message
    await (super(MyWebSocketaHandler, self).write_message(byte_message, binary))
  File "/usr/local/lib/python3.7/site-packages/tornado/websocket.py", line 336, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError

Traceback (most recent call last):
  File "/root/server/proxynt/server/websocket_handler.py", line 152, in on_message_async
    await self.write_message(NatSerialization.dumps(message_dict, key, self.compress_support), binary=True)  # 更新完配置再发给客户端
  File "/root/server/proxynt/server/websocket_handler.py", line 68, in write_message
    await (super(MyWebSocketaHandler, self).write_message(byte_message, binary))
  File "/usr/local/lib/python3.7/site-packages/tornado/websocket.py", line 336, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
```
nginx的配置如下
<img width="547" alt="image" src="https://github.com/user-attachments/assets/7e1deb53-e03c-433c-8294-1999c0484835">

**Comment by MilkywayVainB** [comment]
已解决。。。发现是服务器没有安装python-snappy导致的。。。
